version: "3.9"

services:
  mongo:
    build: .
    container_name: fantasygolf-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fantasygolf
      MONGO_INITDB_ROOT_PASSWORD: fantasygolf
      MONGO_INITDB_DATABASE: fantasygolf
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
